version: '3.8'
services: 
  frontend:
    build:
      context: ./fe_v2
      dockerfile: Dockerfile
    container_name: frontend
    ports:  
      - 80:80
    depends_on:
      - backend
    networks:
      - mynetwork

  mongo_db:
    image: mongo
    restart: unless-stopped
    container_name: mongo-container
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - mynetwork
    command: mongod --bind_ip_all

  mongo_ins:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: mongo-ins-container
    depends_on:
      - mongo_db
    networks:
      - mynetwork

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongo_db:27017/my_db
    depends_on:
      - mongo_db
    networks:
      - mynetwork

volumes:
  mongo_db: {}

networks:
  mynetwork:
    driver: bridge