version: '3.8'
services: 
  # Các cấu hình bổ sung cho dịch vụ frontend
  frontend:
    build:
      context: ./fe_v2
      dockerfile: Dockerfile
    container_name: frontend
    ports:  
      - 80:80
    depends_on:
      - backend
    networks:
      - mynetwork
  # Các cấu hình bổ sung cho dịch vụ mongodb
  mongo_db:
    build: 
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: mongodb_container
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - mynetwork
    command: mongod --bind_ip_all
  # Các cấu hình bổ sung cho dịch vụ backend
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URL: mongodb://mongo_db:27017/
      DB_NAME: my_db
    depends_on:
      - mongo_db
    networks:
      - mynetwork
volumes:
  mongo_db: {}
networks:
  mynetwork:
    driver: bridge
