version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t my-app .
  deploy:
    docker:
      - image: my-app:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Docker image to registry
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push my-registry/my-app:$CIRCLE_SHA1
          environment:
            DOCKERHUB_USERNAME: my-username
            DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
