jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and tag Docker image
          command: |
            docker build -t fe .
            docker tag fe
  deploy:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Docker image to registry
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push my-registry/my-app:$CIRCLE_SHA1
          environment:
            DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
            DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
      - run:
          name: Deploy to production
          command: npm run deploy
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
