version: 2.1

jobs:
  build:
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - store_artifacts:
          path: ~/project/dist
          destination: dist

workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
