name: Talk Desk CI
on:
  push:
    branches: [Thanh]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 54.173.217.245 
          #host: ${{ secrets.HOST }}
          username: ec2-user
          #username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ -d "talkdesk_g5" ]; then
              cd talkdesk_g5
              git pull origin Thanh
              cd ~
            else
                git clone -b Thanh https://github.com/LeHaiDangSPKT/talkdesk_g5.git
            fi
            
      - name: Run back-end and front-end
        uses: appleboy/ssh-action@master
        with:
          host: 54.173.217.245 
          #host: ${{ secrets.HOST }}
          username: ec2-user
          #username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            cd talkdesk_g5
            sudo docker-compose down
            sudo docker system prune --all --force --volumes
            sudo docker-compose up -d
